### PR TITLE
Fix CMake detection of config modules on Python installation

### LINKED ISSUE #671: Python wheel doesn't install CMake config files
When `dqcsim` is installed via `pip`, the CMake config files are not installed (`dqcsimConfig.cmake`, `dqcsimConfigVersion.cmake`). This is expected as `setup.py` has not yet been updated. The easy part is to update this part:

https://github.com/QE-Lab/dqcsim/blob/c0e596ee56e67f6caa067e97e1085a86974b8177/setup.py#L187-L189

The somewhat more complicated thing is that when building the wheel, it would need to call CMake to generate the two CMake config files. Good thing is that it just needs to call CMake for configuration step, not building neither installation.

The command
```
cmake -B build .
```
would generate `build/dqcsimConfig.cmake` and `build/dqcsimConfigVersion.cmake`.

I just don't know how to this packaging step and I guess it would be part of your automated deployment.

### PR DESCRIPTION
**Pull request by mofeing**
Fixes #671.

So the main problem is that CMake needs to be pointed wherever the config files are installed. In a system-wide installation (installing through CMake), config files are installed in the default path `/usr/local/lib/cmake` so no variable needs to be passed. But when installed through `pip`, the installation prefix is arbitrary (depending if you use a system `pip`, Anaconda, a virtualenv, ...). It would be solved by setting `CMAKE_MODULE_PATH`, but it is very cumbersome and I don't think there is an easy way so that virtualenvs could set the `DQCSIM_PREFIX` env variable automatically.

The best solution I found is to install the `cmake` wheel so that the CMake is in the same install prefix as the `dqcsim` wheel. This way `cmake` detects the config modules.

I still have some problems finding the correct path with CMake now, so the PR is not ready to be merged yet.

### CODE REVIEW

**Comment by mofeing** [comment]
Commit https://github.com/QE-Lab/dqcsim/pull/675/commits/251c5dd7491834050e9abf2b460a586785130e0c fixes it!
I've tried to search for `dqcsim` using two different Python installations. Calling `pyenv` you can see that I have the system-installed distribution and Python 3.8.2. `dqcsim` is installed in Python 3.8.2.
```
system
* 3.8.2 (set by /Users/mofeing/.pyenv/version)
```

If I run `cmake --find-package -DNAME=dqcsim -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST` in with system Python active:
```
dqcsim not found.
CMake Error: Problem processing arguments. Aborting.
```

But if I run it with Python 3.8.2 active:
```
dqcsim found.
```

**Comment by mbrobbel** [comment]
Nice!

Can you please rebase on (or merge) master? #676 hopefully fixes the examples workflow for forks.

**Comment by mofeing** [comment]
> Can you please rebase on (or merge) master? #676 hopefully fixes the examples workflow for forks.

Done.

BTW I've just found that environment variables do not seem to do anything. As installation from `pip` is solved, I don't find it critical so I will leave it like that but do not mind mentioning me if you need a fix for that.

**Comment by mbrobbel** [comment]
@mofeing can you please rebase this again? Thanks!

**Comment by mbrobbel** [comment]
Hm, I can't figure out how to get the fork owner for the example workflow. I'll merge this and try to fix that later. Thanks again.

**Pull request merged**
