### PR TITLE
Refactor CMake

### PR DESCRIPTION
**Pull request by mofeing**
As of now, it is not straightforward to develop a plugin in C++. Even if you install the dynamic library and the headers, there is no automatic way for CMake to find them.

Furthermore, current CMakeLists.txt is bloated with 2 different projects depending on whether you are importing it or you are just building it. It evens complicates more when we want to import it but built from source.

As such, I've been working on a refactor of the CMake instructions to try to overcome this problems. This refactor:
- Works with `FetchContent` just as before.
- Supports `DQCSIM_PREFIX`, `DQCSIM_LIB` and `DQCSIM_INC` env variables (but not tested).
- Installs a CMake config module so now it can be used with `find_package`.

If merged importing `dqcsim` into your CMake project is as easy as (considering that it is already installed in your system):
```cmake
find_package(dqcsim 0.2.5 REQUIRED)
```

If there is something you do not agree with, we can modify it :)

### CODE REVIEW

**Comment by mofeing** [comment]
BTW could we add install support for the cli so we could get rid of the mandatory Python workaround?
I don't want to use Python to develop a C++ plugin.

**Comment by mbrobbel** [comment]
Thanks for this!
Can you please rebase on (or merge) `master`? I fixed the issue with the checks.

**Comment by mofeing** [comment]
> Thanks for this!
> Can you please rebase on (or merge) `master`? I fixed the issue with the checks.

Done @mbrobbel

**Comment by mofeing** [comment]
Ah, `find_package` uses versioning to detect the compatible installed package it is looking for. I set compatibility to `SameMajorVersion` because it is the usual thing.

**Review by jvanstraten — APPROVED** [review]
Nice! I remember the toplevel if/else branch in the CMakeLists being a bit of an afterthought, and to be honest Matthijs and I didn't really know what we were doing with CMake anyway. It was mostly just a necessary evil to be hidden by cargo and (also very much a necessary evil) Python setuptools. So, in my opinion, any improvement that doesn't break CI is welcome.

**Comment by mbrobbel** [comment]
> BTW could we add install support for the cli so we could get rid of the mandatory Python workaround?
> I don't want to use Python to develop a C++ plugin.

Can you please create a separate issue for this?

It should be possible to install the cli (or other bin targets) with cargo: `cargo install dqcsim --features cli`. 

https://github.com/QE-Lab/dqcsim/blob/f18f0326cc1c4ac840e5003e76df98d64a8ac202/rust/Cargo.toml#L47-L51
However, this is currently broken, and I would have to fix something.

**Comment by mofeing** [comment]
> Nice! I remember the toplevel if/else branch in the CMakeLists being a bit of an afterthought, and to be honest Matthijs and I didn't really know what we were doing with CMake anyway. It was mostly just a necessary evil to be hidden by cargo and (also very much a necessary evil) Python setuptools. So, in my opinion, any improvement that doesn't break CI is welcome.

I totally feel you. CMake is a pain-in-the-ass but it is still the best for developing in C++. Love the way Cargo manages everything.

> Can you please create a separate issue for this?

Ok. Going.

> It should be possible to install the cli (or other bin targets) with cargo: `cargo install dqcsim --features cli`.

This command is failing to me. I'm reporting an issue.

> https://github.com/QE-Lab/dqcsim/blob/f18f0326cc1c4ac840e5003e76df98d64a8ac202/rust/Cargo.toml#L47-L51
> 
> However, this is currently broken, and I would have to fix something.

How about decomposing that huge rust projects into different,smaller projects inside the same workspace? Like [serde](https://github.com/serde-rs/serde) or [yew](https://github.com/yewstack/yew) and other rust projects do.
Or use a meta-crate like [num](https://github.com/rust-num/num) does?

**Comment by mbrobbel** [comment]
> This command is failing to me. I'm reporting an issue.

I know how to fix it. It should be fixed when I push a new release to crates.io.

> How about decomposing that huge rust projects into different,smaller projects inside the same workspace? Like [serde](https://github.com/serde-rs/serde) or [yew](https://github.com/yewstack/yew) and other rust projects do.
> Or use a meta-crate like [num](https://github.com/rust-num/num) does?

We did consider these different methods, but in the end we decided to use features. Workspace support was lacking for something that we were doing CI I think. Not sure.

I also just noticed that our example checks are using the main branch so they weren't testing against the new CMake file. The CMake fetchcontent example is now failing: https://github.com/QE-Lab/dqcsim/runs/1441908496. Does it still work for you locally?

**Comment by mofeing** [comment]
> I know how to fix it. It should be fixed when I push a new release to crates.io.

Nice 👍 

> I also just noticed that our example checks are using the main branch so they weren't testing against the new CMake file. The CMake fetchcontent example is now failing: https://github.com/QE-Lab/dqcsim/runs/1441908496. Does it still work for you locally?

It is working for me. I'm using macOS 10.15.

Output of `cmake .`:
```
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at _deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Deprecation Warning at _deps/googletest-src/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at _deps/googletest-src/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found PythonInterp: /Users/mofeing/.pyenv/shims/python (found version "3.8.2") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Failed to find LLVM FileCheck
-- Found Git: /usr/local/bin/git (found version "2.29.2") 
-- git Version: v1.5.2-7fa6f1f9
-- Version: 1.5.2
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Success
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Success
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Using the single-header code from /Users/mofeing/Develop/dqcsim/examples/cmake-fetchcontent/project/_deps/json-src/single_include/
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mofeing/Develop/dqcsim/examples/cmake-fetchcontent/project
```

Output of `make`:
```
Scanning dependencies of target crate
[ 10%] Creating directories for 'crate'
[ 20%] No download step for 'crate'
[ 30%] No update step for 'crate'
[ 40%] No patch step for 'crate'
[ 50%] No configure step for 'crate'
[ 60%] Performing build step for 'crate'
   Compiling proc-macro2 v1.0.24
   Compiling libc v0.2.80
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.48
   Compiling autocfg v1.0.0
   Compiling cfg-if v0.1.10
   Compiling serde_derive v1.0.114
   Compiling serde v1.0.114
   Compiling getrandom v0.1.14
   Compiling ppv-lite86 v0.2.8
   Compiling lazy_static v1.4.0
   Compiling memchr v2.3.3
   Compiling ryu v1.0.5
   Compiling bitflags v1.2.1
   Compiling serde_json v1.0.59
   Compiling unicode-width v0.1.8
   Compiling remove_dir_all v0.5.3
   Compiling unicode-segmentation v1.6.0
   Compiling log v0.4.11
   Compiling vec_map v0.8.2
   Compiling byteorder v1.3.4
   Compiling ansi_term v0.11.0
   Compiling cbindgen v0.14.3
   Compiling itoa v0.4.6
   Compiling strsim v0.8.0
   Compiling maybe-uninit v2.0.0
   Compiling regex-syntax v0.6.21
   Compiling adler v0.2.3
   Compiling gimli v0.23.0
   Compiling failure_derive v0.1.8
   Compiling object v0.22.0
   Compiling rustc-demangle v0.1.16
   Compiling cfg-if v1.0.0
   Compiling linked-hash-map v0.5.3
   Compiling fnv v1.0.7
   Compiling dtoa v0.4.6
   Compiling half v1.6.0
   Compiling pathdiff v0.2.0
   Compiling humantime v2.0.1
   Compiling whoami v0.9.0
   Compiling integer-sqrt v0.1.3
   Compiling strum v0.19.5
   Compiling ref_thread_local v0.0.0
   Compiling is_executable v0.1.2
   Compiling thread_local v1.0.1
   Compiling textwrap v0.11.0
   Compiling num-traits v0.2.12
   Compiling miniz_oxide v0.4.3
   Compiling crossbeam-utils v0.7.2
   Compiling heck v0.3.1
   Compiling yaml-rust v0.4.4
   Compiling atty v0.2.14
   Compiling dirs-sys v0.3.5
   Compiling aho-corasick v0.7.13
   Compiling quote v1.0.7
   Compiling clap v2.33.1
   Compiling dirs v2.0.2
   Compiling rand_core v0.5.1
   Compiling crossbeam-channel v0.4.2
   Compiling addr2line v0.14.0
   Compiling term v0.6.1
   Compiling regex v1.3.9
   Compiling rand_chacha v0.2.2
   Compiling float-cmp v0.8.0
   Compiling num-complex v0.3.0
   Compiling backtrace v0.3.54
   Compiling rand v0.7.3
   Compiling tempfile v3.1.0
   Compiling uuid v0.8.1
   Compiling synstructure v0.12.4
   Compiling strum_macros v0.18.0
   Compiling failure v0.1.8
   Compiling toml v0.5.6
   Compiling bincode v1.3.1
   Compiling serde_cbor v0.11.1
   Compiling serde-transcode v1.1.0
   Compiling serde_yaml v0.8.13
   Compiling ipc-channel v0.14.1
   Compiling dqcsim v0.2.5 (/Users/mofeing/Develop/dqcsim/examples/cmake-fetchcontent/project/_deps/dqcsim-src/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 22s
[ 70%] No install step for 'crate'
[ 80%] Completed 'crate'
[ 80%] Built target crate
Scanning dependencies of target main
[ 90%] Building CXX object CMakeFiles/main.dir/main.cpp.o
[100%] Linking CXX executable main
[100%] Built target main
```

**Comment by mofeing** [comment]
@mbrobbel Some strange behaviour. If I use CMake to generate a Makefile (the default from CLI), building works perfectly: `crate` dependency is detected and it is built before the example.

But if I use it to generate a Ninja file (the default using the CMake Tools ext in VSCode), Ninja fails to detect the `crate` dependency and you need to manually run first `ninja crate`. After that, just running `ninja` works.

As I see, the CI is not using ninja but could it be that it is not correctly building the `crate` dependency? I guess this is not the real problem but trying is just as easy as running `make crate` before `make` and after `cmake`.

**Comment by mbrobbel** [comment]
It looks like a linking path issue. I'm testing a fix now in #668. 
I'm not sure about that Ninja issue? I've only been using make.

**Comment by mofeing** [comment]
Don't know. The ninja issue seems like a CMake bug to me.

**Comment by mbrobbel** [comment]
@mofeing `cargo install dqcsim --features cli` should now work 👍

**Pull request merged**
